//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaBazar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieWalaDbEntities : DbContext
    {
        public MovieWalaDbEntities()
            : base("name=MovieWalaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consumer> Consumers { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Official> Officials { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
